### ISSUE TITLE
Flashli doesn't work with OpenSuse Leap in Version 15.4

### ISSUE THREAD

**Issue by freebeasty** [protectli-root/protectli-firmware-updater#30]
hi!

I want to install the traditional BIOS and replace opencore.

The script uses a wrong filename for the nic interface.

In my case it has to be :
cat /sys/class/net/eth0/address

instead of:
/sys/class/net/enp1s0/address

Can you help me ?

Thanks in advance,
Raphael

I get this output: 

sh: /bin/clear: No such file or directory
 ______   ______     ______     ______   ______     ______     ______   __         __
/\  == \ /\  == \   /\  __ \   /\__  _\ /\  ___\   /\  ___\   /\__  _\ /\ \       /\ \
\ \  _-/ \ \  __<   \ \ \/\ \  \/_/\ \/ \ \  __\   \ \ \____  \/_/\ \/ \ \ \____  \ \ \
 \ \_\    \ \_\ \_\  \ \_____\    \ \_\  \ \_____\  \ \_____\    \ \_\  \ \_____\  \ \_\
  \/_/     \/_/ /_/   \/_____/     \/_/   \/_____/   \/_____/     \/_/   \/_____/   \/_/
_________________________________________________________________________________________

/bin/cat: /sys/class/net/enp1s0/address: No such file or directory
Traceback (most recent call last):
  File "./flashbios", line 336, in <module>
    main()
  File "./flashbios", line 277, in main
    device = hardware.get_protectli_device(DEBUGMODE, check_mac())
  File "./flashbios", line 152, in check_mac
    device_mac = str(hardware.get_mac(DEBUGMODE))
  File "/root/protectli-firmware-updater-1.1.32/flashli/hardware.py", line 162, in get_mac
    device_mac = str(subprocess.check_output(['/bin/cat', other_unites_mac_dir], shell=False).decode('utf-8'))
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/bin/cat', '/sys/class/net/enp1s0/address']' returned non-zero exit status 1.

**Comment by SergeyKonst3** [comment]
Hello, 
Sorry for the late response.

We haven't tested the script in OpenSuse so we cannot account for the issues that arise. If you can we do recommend using Ubuntu as it is the main OS we test with. 

With that being said I have attached a modified flashli script files that changes the enp1s0 to eth0 and also commented out the /bin/clear as it might seem that function is not present.

Please replace the flashbios file and the hardware.py file (located in the fla
shli folder) in the copy of the script that you have.

These modifications have not been tested in OpenSuse and might not work or there might be other issues that arise that can end up bricking the device,  please proceed at your own risk.
I also want to mention that this script is meant to be run on Protectli Vaults.

I do hope that this helps. If you have any questions please let us know.

[protectli-firmware-updater-modified-files.zip](https://github.com/protectli-root/protectli-firmware-updater/files/10886784/protectli-firmware-updater-modified-files.zip)
