### ISSUE TITLE
Several issues with flashli when running from a Gentoo Live USB image

### ISSUE THREAD

**Issue by Kumba43** [protectli-root/protectli-firmware-updater#31]
Ran into a few issues using flashli from a Gentoo amd64 live USB that's typically used for installation purposes.  The specific Gentoo image is a minimal install autobuild ISO, built on 2023-05-14.  Can't link to it, as the autobuilds get updated automatically and older images removed.
```
# uname -a
Linux livecd 6.1.27-gentoo-r1-x86_64 #1 SMP PREEMPT_DYNAMIC Sun May 14 18:23:09 UTC 2023 x86_64 Intel(R) Celeron(R) CPU 3865U @ 1.80GHz GenuineIntel GNU/Linux

# /lib64/libc.so.6
GNU C Library (Gentoo 2.36-r8 p10) stable release version 2.36.
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 12.2.1 20230428.
libc ABIs: UNIQUE IFUNC ABSOLUTE
Minimum supported kernel: 3.2.0
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.

```
- Running flashbios attempts to call `/bin/clear`.  Due to Linux distros consolidating core binaries into `/usr/bin`, this isn't guaranteed to work, as not all systems provide `/bin` symlinks to programs that have been moved to `/usr/bin`.  Suggest that flashbios try to look for 'clear' in `/bin` first, and if found, invoke it; else, look in `/usr/bin` second and, if found, invoke it; else, error out.
- Received the following Python traceback from `flashli/hardware.py`:
  ```
  Traceback (most recent call last):
    File "/mnt/cdrom/flashli/./flashbios", line 15, in <module>
      from flashli import configurations, hardware
    File "/mnt/cdrom/flashli/flashli/hardware.py", line 3, in <module>
      from nis import match
  ModuleNotFoundError: No module named 'nis'
  ```
  - Commenting-out the import statement seems to be a good workaround.  The `match` function does not seem to be used in that specific module, so perhaps this is old code that needs to be removed?
- Both `flashrom` and `flashrom_v2` in the `vendor` subfolder are compiled as dynamic ELF executables, and this is not a portable solution if flashli is intended to be run agnostically from any modern Linux distribution.  In the case of this Gentoo USB image, I receive the following error:
  `vendor/flashrom: symbol lookup error: vendor/flashrom: undefined symbol: pci_filter_init, version LIBPCI_3.3
  `

  - Checking with the `file` tool, I can see that `flashrom` is a dynamic ELF:
    ```
    # file vendor/flashrom
    vendor/flashrom: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked,
    interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0,
    BuildID[sha1]=79da4c31b8f4725b34a7e83887d60583e951fb32, not stripped
    
    ```
- Firmware flashing utilities should be compiled as static ELF executables to avoid cases where the Linux userland that they are running under isn't missing important libraries or symbols that are needed for these tools to work.
  ```
  # ldd vendor/flashrom
          linux-vdso.so.1 (0x00007fffdf7cd000)
          libpci.so.3 => /usr/lib64/libpci.so.3 (0x00007fb6866f5000)
          librt.so.1 => /lib64/librt.so.1 (0x00007fb6866f0000)
          libc.so.6 => /lib64/libc.so.6 (0x00007fb68651d000)
          libz.so.1 => /lib64/libz.so.1 (0x00007fb686503000)
          libudev.so.1 => /lib64/libudev.so.1 (0x00007fb6864c8000)
          /lib64/ld-linux-x86-64.so.2 (0x00007fb6867db000)
  
  ```

**Comment by SergeyKonst3** [comment]
Hello Kumba43,

We intended Flashli to work in Ubuntu and have designed it as such. Sadly we haven't had a chance to test it on other Linux distributions.  
We will look into verifying 'clear' as well as removing 'match' as it does look like it code that is not used. 

Regarding flashrom we will try to compile it in static ELF to make it applicable in more cases.

These changes might not make it into the upcoming update but we will try to add them in the following update.

Apologizes for any inconveniences.
